#!/usr/bin/env bash
# script that transfers a file from our client to a server:
# Check if the required number of command-line arguments is provided
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

# Assign command-line arguments to variables
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Disable strict host key checking for SCP
scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# Check if the file transfer was successful
if [ $? -eq 0 ]; then
	echo "File transfer was successful"
else
	echo "File transfer failed"
fi
