#!/usr/bin/env bash
# a Bash script that pings
# an IP address passed as an argument.
# Accepts a string as an arg
# Ping the IP 5 times
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
# if 0 arg passed

if [ $# -eq 0 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

ip_address=$1

echo "Pinging $ip_address 5 times..."
ping -c 5 $ip_address
