#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s
# Nginx installation from listening on port 80.
# Feel free to install whatever tool you need, start and destroy

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
