#!/usr/bin/env bash
# a script that displays "To infinity and beyond" indefinitely
# In between each iteration of loop, adds a sleep 2

cont=1
while [ "$cont" -lt 2 ];
do
    echo "To infinity and beyond";
    sleep 2
done
