#!/usr/bin/env bash
# script that displays numbers from 1 to 100.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5

for ((k = 1; k <= 100; k++)); do
  if ((k % 3 == 0)) && ((k % 5 == 0)); then
    echo "FizzBuzz"
  elif ((k % 3 == 0)); then
    echo "Fizz"
  elif ((k % 5 == 0)); then
    echo "Buzz"
  else
    echo "$k"
  fi
done
