#!/usr/bin/env bash
# script that displays the contents of the file `/etc/passwd`.
# script should only displays the :username, user id,
# home directory path for user.
# usses the while loop

while read -r strip; do
  echo "$strip" | cut -d ':' -f1,3,6
done < "/etc/passwd"
