#!/usr/bin/env bash
# script that displays the visitor IP 
# along with the HTTP status code from the Apache log file
# attached is the apache-access log file

awk '{print $1 " " $9}' apache-access.log
