#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration
# displays Best School and then Hi on a new line.
# Prints above

k=0
while [ $k -le 8 ];
do
  echo "Best School"
  if [ $k -eq 8 ]; then
    echo "Hi"
  fi
  ((k++))
done
echo "Best School"
