#!/usr/bin/env bash
# a Bash script that configures
# an Ubuntu server with the below requirements.
# in the script localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.


cp /etc/hosts ~/hosts.edit
echo "127.0.0.2		localhost" > ~/hosts.edit
echo "8.8.8.8		facebook.com" >> ~/hosts.edit
cp -f ~/hosts.edit /etc/hosts
